// <auto-generated />
namespace toofz.NecroDancer.Leaderboards.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LimeZincAfghanHound : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LimeZincAfghanHound));
        
        string IMigrationMetadata.Id
        {
            get { return "201707172139340_LimeZinc﻿AfghanHound"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
