//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(toofz.NecroDancer.Leaderboards.LeaderboardsContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsad4f08decf78b9f3a0d5f75964f43fc7c6da8703c058df6a09a1e5b9247f82ad))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySetsad4f08decf78b9f3a0d5f75964f43fc7c6da8703c058df6a09a1e5b9247f82ad : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "ad4f08decf78b9f3a0d5f75964f43fc7c6da8703c058df6a09a1e5b9247f82ad"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.Character")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.DailyEntry")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.DailyLeaderboard")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.Product")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.Player")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.Entry")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.Leaderboard")
            {
                return GetView6();
            }

            if (extentName == "CodeFirstDatabase.Mode")
            {
                return GetView7();
            }

            if (extentName == "CodeFirstDatabase.Run")
            {
                return GetView8();
            }

            if (extentName == "LeaderboardsContext.Characters")
            {
                return GetView9();
            }

            if (extentName == "LeaderboardsContext.DailyEntries")
            {
                return GetView10();
            }

            if (extentName == "LeaderboardsContext.DailyLeaderboards")
            {
                return GetView11();
            }

            if (extentName == "LeaderboardsContext.Products")
            {
                return GetView12();
            }

            if (extentName == "LeaderboardsContext.Players")
            {
                return GetView13();
            }

            if (extentName == "LeaderboardsContext.Entries")
            {
                return GetView14();
            }

            if (extentName == "LeaderboardsContext.Leaderboards")
            {
                return GetView15();
            }

            if (extentName == "LeaderboardsContext.Modes")
            {
                return GetView16();
            }

            if (extentName == "LeaderboardsContext.Runs")
            {
                return GetView17();
            }

            if (extentName == "CodeFirstDatabase.Replay")
            {
                return GetView18();
            }

            if (extentName == "LeaderboardsContext.Replays")
            {
                return GetView19();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Character.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Character
        [CodeFirstDatabaseSchema.Character](T1.Character_CharacterId, T1.Character_Name, T1.Character_DisplayName)
    FROM (
        SELECT 
            T.CharacterId AS Character_CharacterId, 
            T.Name AS Character_Name, 
            T.DisplayName AS Character_DisplayName, 
            True AS _from0
        FROM LeaderboardsContext.Characters AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.DailyEntry.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DailyEntry
        [CodeFirstDatabaseSchema.DailyEntry](T1.DailyEntry_LeaderboardId, T1.DailyEntry_Rank, T1.DailyEntry_SteamId, T1.DailyEntry_ReplayId, T1.DailyEntry_Score, T1.DailyEntry_Zone, T1.DailyEntry_Level)
    FROM (
        SELECT 
            T.LeaderboardId AS DailyEntry_LeaderboardId, 
            T.Rank AS DailyEntry_Rank, 
            T.SteamId AS DailyEntry_SteamId, 
            T.ReplayId AS DailyEntry_ReplayId, 
            T.Score AS DailyEntry_Score, 
            T.Zone AS DailyEntry_Zone, 
            T.Level AS DailyEntry_Level, 
            True AS _from0
        FROM LeaderboardsContext.DailyEntries AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.DailyLeaderboard.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DailyLeaderboard
        [CodeFirstDatabaseSchema.DailyLeaderboard](T1.DailyLeaderboard_LeaderboardId, T1.DailyLeaderboard_LastUpdate, T1.DailyLeaderboard_Name, T1.DailyLeaderboard_DisplayName, T1.DailyLeaderboard_IsProduction, T1.DailyLeaderboard_ProductId, T1.DailyLeaderboard_Date)
    FROM (
        SELECT 
            T.LeaderboardId AS DailyLeaderboard_LeaderboardId, 
            T.LastUpdate AS DailyLeaderboard_LastUpdate, 
            T.Name AS DailyLeaderboard_Name, 
            T.DisplayName AS DailyLeaderboard_DisplayName, 
            T.IsProduction AS DailyLeaderboard_IsProduction, 
            T.ProductId AS DailyLeaderboard_ProductId, 
            T.Date AS DailyLeaderboard_Date, 
            True AS _from0
        FROM LeaderboardsContext.DailyLeaderboards AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Product.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Product
        [CodeFirstDatabaseSchema.Product](T1.Product_ProductId, T1.Product_Name, T1.Product_DisplayName)
    FROM (
        SELECT 
            T.ProductId AS Product_ProductId, 
            T.Name AS Product_Name, 
            T.DisplayName AS Product_DisplayName, 
            True AS _from0
        FROM LeaderboardsContext.Products AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Player.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Player
        [CodeFirstDatabaseSchema.Player](T1.Player_SteamId, T1.Player_LastUpdate, T1.Player_Exists, T1.Player_Name, T1.Player_Avatar)
    FROM (
        SELECT 
            T.SteamId AS Player_SteamId, 
            T.LastUpdate AS Player_LastUpdate, 
            T.[Exists] AS Player_Exists, 
            T.Name AS Player_Name, 
            T.Avatar AS Player_Avatar, 
            True AS _from0
        FROM LeaderboardsContext.Players AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Entry.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Entry
        [CodeFirstDatabaseSchema.Entry](T1.Entry_LeaderboardId, T1.Entry_Rank, T1.Entry_SteamId, T1.Entry_ReplayId, T1.Entry_Score, T1.Entry_Zone, T1.Entry_Level)
    FROM (
        SELECT 
            T.LeaderboardId AS Entry_LeaderboardId, 
            T.Rank AS Entry_Rank, 
            T.SteamId AS Entry_SteamId, 
            T.ReplayId AS Entry_ReplayId, 
            T.Score AS Entry_Score, 
            T.Zone AS Entry_Zone, 
            T.Level AS Entry_Level, 
            True AS _from0
        FROM LeaderboardsContext.Entries AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Leaderboard.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Leaderboard
        [CodeFirstDatabaseSchema.Leaderboard](T1.Leaderboard_LeaderboardId, T1.Leaderboard_LastUpdate, T1.Leaderboard_Name, T1.Leaderboard_DisplayName, T1.Leaderboard_IsProduction, T1.Leaderboard_ProductId, T1.Leaderboard_ModeId, T1.Leaderboard_RunId, T1.Leaderboard_CharacterId, T1.Leaderboard_IsCustomMusic, T1.Leaderboard_IsCoOp)
    FROM (
        SELECT 
            T.LeaderboardId AS Leaderboard_LeaderboardId, 
            T.LastUpdate AS Leaderboard_LastUpdate, 
            T.Name AS Leaderboard_Name, 
            T.DisplayName AS Leaderboard_DisplayName, 
            T.IsProduction AS Leaderboard_IsProduction, 
            T.ProductId AS Leaderboard_ProductId, 
            T.ModeId AS Leaderboard_ModeId, 
            T.RunId AS Leaderboard_RunId, 
            T.CharacterId AS Leaderboard_CharacterId, 
            T.IsCustomMusic AS Leaderboard_IsCustomMusic, 
            T.IsCoOp AS Leaderboard_IsCoOp, 
            True AS _from0
        FROM LeaderboardsContext.Leaderboards AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Mode.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Mode
        [CodeFirstDatabaseSchema.Mode](T1.Mode_ModeId, T1.Mode_Name, T1.Mode_DisplayName)
    FROM (
        SELECT 
            T.ModeId AS Mode_ModeId, 
            T.Name AS Mode_Name, 
            T.DisplayName AS Mode_DisplayName, 
            True AS _from0
        FROM LeaderboardsContext.Modes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Run.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Run
        [CodeFirstDatabaseSchema.Run](T1.Run_RunId, T1.Run_Name, T1.Run_DisplayName)
    FROM (
        SELECT 
            T.RunId AS Run_RunId, 
            T.Name AS Run_Name, 
            T.DisplayName AS Run_DisplayName, 
            True AS _from0
        FROM LeaderboardsContext.Runs AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Characters.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Characters
        [toofz.NecroDancer.Leaderboards.Character](T1.Character_CharacterId, T1.Character_Name, T1.Character_DisplayName)
    FROM (
        SELECT 
            T.CharacterId AS Character_CharacterId, 
            T.Name AS Character_Name, 
            T.DisplayName AS Character_DisplayName, 
            True AS _from0
        FROM CodeFirstDatabase.Character AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.DailyEntries.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DailyEntries
        [toofz.NecroDancer.Leaderboards.DailyEntry](T1.DailyEntry_LeaderboardId, T1.DailyEntry_Rank, T1.DailyEntry_SteamId, T1.DailyEntry_ReplayId, T1.DailyEntry_Score, T1.DailyEntry_Zone, T1.DailyEntry_Level)
    FROM (
        SELECT 
            T.LeaderboardId AS DailyEntry_LeaderboardId, 
            T.Rank AS DailyEntry_Rank, 
            T.SteamId AS DailyEntry_SteamId, 
            T.ReplayId AS DailyEntry_ReplayId, 
            T.Score AS DailyEntry_Score, 
            T.Zone AS DailyEntry_Zone, 
            T.Level AS DailyEntry_Level, 
            True AS _from0
        FROM CodeFirstDatabase.DailyEntry AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.DailyLeaderboards.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DailyLeaderboards
        [toofz.NecroDancer.Leaderboards.DailyLeaderboard](T1.DailyLeaderboard_LeaderboardId, T1.DailyLeaderboard_LastUpdate, T1.DailyLeaderboard_Name, T1.DailyLeaderboard_DisplayName, T1.DailyLeaderboard_IsProduction, T1.DailyLeaderboard_ProductId, T1.DailyLeaderboard_Date)
    FROM (
        SELECT 
            T.LeaderboardId AS DailyLeaderboard_LeaderboardId, 
            T.LastUpdate AS DailyLeaderboard_LastUpdate, 
            T.Name AS DailyLeaderboard_Name, 
            T.DisplayName AS DailyLeaderboard_DisplayName, 
            T.IsProduction AS DailyLeaderboard_IsProduction, 
            T.ProductId AS DailyLeaderboard_ProductId, 
            T.Date AS DailyLeaderboard_Date, 
            True AS _from0
        FROM CodeFirstDatabase.DailyLeaderboard AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Products.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Products
        [toofz.NecroDancer.Leaderboards.Product](T1.Product_ProductId, T1.Product_Name, T1.Product_DisplayName)
    FROM (
        SELECT 
            T.ProductId AS Product_ProductId, 
            T.Name AS Product_Name, 
            T.DisplayName AS Product_DisplayName, 
            True AS _from0
        FROM CodeFirstDatabase.Product AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Players.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Players
        [toofz.NecroDancer.Leaderboards.Player](T1.Player_SteamId, T1.Player_LastUpdate, T1.Player_Exists, T1.Player_Name, T1.Player_Avatar)
    FROM (
        SELECT 
            T.SteamId AS Player_SteamId, 
            T.LastUpdate AS Player_LastUpdate, 
            T.[Exists] AS Player_Exists, 
            T.Name AS Player_Name, 
            T.Avatar AS Player_Avatar, 
            True AS _from0
        FROM CodeFirstDatabase.Player AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Entries.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Entries
        [toofz.NecroDancer.Leaderboards.Entry](T1.Entry_LeaderboardId, T1.Entry_Rank, T1.Entry_SteamId, T1.Entry_ReplayId, T1.Entry_Score, T1.Entry_Zone, T1.Entry_Level)
    FROM (
        SELECT 
            T.LeaderboardId AS Entry_LeaderboardId, 
            T.Rank AS Entry_Rank, 
            T.SteamId AS Entry_SteamId, 
            T.ReplayId AS Entry_ReplayId, 
            T.Score AS Entry_Score, 
            T.Zone AS Entry_Zone, 
            T.Level AS Entry_Level, 
            True AS _from0
        FROM CodeFirstDatabase.Entry AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Leaderboards.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Leaderboards
        [toofz.NecroDancer.Leaderboards.Leaderboard](T1.Leaderboard_LeaderboardId, T1.Leaderboard_LastUpdate, T1.Leaderboard_Name, T1.Leaderboard_DisplayName, T1.Leaderboard_IsProduction, T1.Leaderboard_ProductId, T1.Leaderboard_ModeId, T1.Leaderboard_RunId, T1.Leaderboard_CharacterId, T1.Leaderboard_IsCustomMusic, T1.Leaderboard_IsCoOp)
    FROM (
        SELECT 
            T.LeaderboardId AS Leaderboard_LeaderboardId, 
            T.LastUpdate AS Leaderboard_LastUpdate, 
            T.Name AS Leaderboard_Name, 
            T.DisplayName AS Leaderboard_DisplayName, 
            T.IsProduction AS Leaderboard_IsProduction, 
            T.ProductId AS Leaderboard_ProductId, 
            T.ModeId AS Leaderboard_ModeId, 
            T.RunId AS Leaderboard_RunId, 
            T.CharacterId AS Leaderboard_CharacterId, 
            T.IsCustomMusic AS Leaderboard_IsCustomMusic, 
            T.IsCoOp AS Leaderboard_IsCoOp, 
            True AS _from0
        FROM CodeFirstDatabase.Leaderboard AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Modes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Modes
        [toofz.NecroDancer.Leaderboards.Mode](T1.Mode_ModeId, T1.Mode_Name, T1.Mode_DisplayName)
    FROM (
        SELECT 
            T.ModeId AS Mode_ModeId, 
            T.Name AS Mode_Name, 
            T.DisplayName AS Mode_DisplayName, 
            True AS _from0
        FROM CodeFirstDatabase.Mode AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Runs.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Runs
        [toofz.NecroDancer.Leaderboards.Run](T1.Run_RunId, T1.Run_Name, T1.Run_DisplayName)
    FROM (
        SELECT 
            T.RunId AS Run_RunId, 
            T.Name AS Run_Name, 
            T.DisplayName AS Run_DisplayName, 
            True AS _from0
        FROM CodeFirstDatabase.Run AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Replay.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Replay
        [CodeFirstDatabaseSchema.Replay](T1.Replay_ReplayId, T1.Replay_ErrorCode, T1.Replay_Seed, T1.Replay_Version, T1.Replay_KilledBy, T1.Replay_Uri)
    FROM (
        SELECT 
            T.ReplayId AS Replay_ReplayId, 
            T.ErrorCode AS Replay_ErrorCode, 
            T.Seed AS Replay_Seed, 
            T.Version AS Replay_Version, 
            T.KilledBy AS Replay_KilledBy, 
            T.Uri AS Replay_Uri, 
            True AS _from0
        FROM LeaderboardsContext.Replays AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for LeaderboardsContext.Replays.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Replays
        [toofz.NecroDancer.Leaderboards.Replay](T1.Replay_ReplayId, T1.Replay_ErrorCode, T1.Replay_Seed, T1.Replay_Version, T1.Replay_KilledBy, T1.Replay_Uri)
    FROM (
        SELECT 
            T.ReplayId AS Replay_ReplayId, 
            T.ErrorCode AS Replay_ErrorCode, 
            T.Seed AS Replay_Seed, 
            T.Version AS Replay_Version, 
            T.KilledBy AS Replay_KilledBy, 
            T.Uri AS Replay_Uri, 
            True AS _from0
        FROM CodeFirstDatabase.Replay AS T
    ) AS T1");
        }
    }
}
